//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkoutDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPerm
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool PaidUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string LastUser { get; set; }
        public double Height { get; set; }
        public double Weight { get; set; }
        public bool Lbs_Kilos { get; set; }
        public string Email { get; set; }
    }
}
