//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkoutDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWorkout
    {
        public string WorkoutName { get; set; }
        public double numSets { get; set; }
        public double numReps { get; set; }
        public int UserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int WorkoutID { get; set; }
    }
}
