//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkoutDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGoal
    {
        public int GoalID { get; set; }
        public int UserID { get; set; }
        public double WeightGoal { get; set; }
    }
}
