//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkoutDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMax
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int WorkoutID { get; set; }
        public double Maxlbs { get; set; }
        public double MaxKilos { get; set; }
        public double MaxGoal { get; set; }
    }
}
