//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkoutDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMuscleFatigue
    {
        public int UserID { get; set; }
        public double Chest { get; set; }
        public System.DateTime ChestLastUseDate { get; set; }
        public double Calves { get; set; }
        public System.DateTime CalvesLastUseDate { get; set; }
        public double Hamstring { get; set; }
        public System.DateTime HamstringLastUseDate { get; set; }
        public double Quadriceps { get; set; }
        public System.DateTime QuadricepsLastUseDate { get; set; }
        public double Glutes { get; set; }
        public System.DateTime GlutesLastUseDate { get; set; }
        public double Biceps { get; set; }
        public System.DateTime BicepsLastUseDate { get; set; }
        public double Triceps { get; set; }
        public System.DateTime TricepsLastUseDate { get; set; }
        public double Forearms { get; set; }
        public System.DateTime ForearmsLastUseDate { get; set; }
        public double Trapezious { get; set; }
        public System.DateTime TrapeziousLastUseDate { get; set; }
        public double LatissimusDorsi { get; set; }
        public System.DateTime LatissismusDorsiLastUseDate { get; set; }
        public double HipAbductors { get; set; }
        public System.DateTime HipAbductorsLastUseDate { get; set; }
        public double HipAdductors { get; set; }
        public System.DateTime HipAdductorsLastUseDate { get; set; }
        public System.DateTime lastUpdate { get; set; }
    }
}
