//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkoutDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workout
    {
        public string WorkoutName { get; set; }
        public string MuscleGroup { get; set; }
        public Nullable<double> MuscleStrainMultiplier { get; set; }
        public int WorkoutID { get; set; }
    }
}
